### ISSUE TITLE
Issue on the frontend "unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.4.3)"

### ISSUE THREAD

**Issue by MatteoGauthier** [tomhirst/solidity-nextjs-starter#1]
Hello firstly thanks for this project, it will be useful for a lot of people. I noticed and error after completing all the steps. 
![image](https://user-images.githubusercontent.com/32040951/128318413-57c0e424-209c-48a0-904a-78f14125db3f.png)

**Comment by tomhirst** [comment]
Hi @MatteoGauthier, thanks for trying the repo!

I've just merged a PR that should solve this issue here: https://github.com/tomhirst/solidity-nextjs-starter/pull/2

LMK how you get on.
